apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
 name: cis-compliance-hypershift
 namespace: openshift-compliance
profiles:
 - name: cis-compliance-hypershift
   kind: TailoredProfile
   apiGroup: compliance.openshift.io/v1alpha1
 - name: ocp4-cis-node
   kind: Profile
   apiGroup: compliance.openshift.io/v1alpha1
settingsRef:
 name: default
 kind: ScanSetting
 apiGroup: compliance.openshift.io/v1alpha1